const std = @import("std");

/// Wayland protocol XMLs whose glue we generate at build time with `wayland-scanner`.
/// Core `wl_*` interfaces live in libwayland-client itself; everything else needs its
/// interface tables compiled into the binary (`private-code`).
const protocol_xmls = [_][]const u8{
    // NB: xdg-shell, xdg-decoration, cursor-shape-v1, tablet-v2 and appmenu are generated by
    // zicro now (its own Wayland backend), and zicro's protocol tables are linked into
    // our binary — so we must NOT also generate them here or the interface symbols
    // collide at link time.
    "/usr/share/wayland-protocols/staging/ext-background-effect/ext-background-effect-v1.xml",
    // GPU frames land in the video subsurface as dmabufs (zero-copy path).
    "/usr/share/wayland-protocols/stable/linux-dmabuf/linux-dmabuf-v1.xml",
    // HiDPI: physically-sized buffers presented at logical size (crisp text on
    // fractionally scaled outputs — KDE "Scale: 1.1" etc.).
    "/usr/share/wayland-protocols/stable/viewporter/viewporter.xml",
    "/usr/share/wayland-protocols/staging/fractional-scale/fractional-scale-v1.xml",
};

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    // Everything zrame draws is per-pixel software rendering; Debug builds can't hold
    // 60 Hz on the demos, so optimized is the default (-Doptimize=Debug to override).
    const optimize = b.option(std.builtin.OptimizeMode, "optimize", "Prioritize performance, safety, or binary size") orelse .ReleaseFast;

    const zicro = b.dependency("zicro", .{ .target = target, .optimize = optimize });

    // The zrame library module: the window/frame layer of the Frame architecture.
    const zrame = b.addModule("zrame", .{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
        .imports = &.{
            .{ .name = "zicro", .module = zicro.module("zicro") },
        },
    });
    // The window transport is per-OS: Wayland on Linux (client-side glass chrome, sd-bus
    // tray/menu, dmabuf video), a native GDI window on Windows. Only link and generate the
    // Linux stack for a Linux target; on Windows link the Win32 GUI libraries instead.
    if (target.result.os.tag == .linux) {
        zrame.linkSystemLibrary("wayland-client", .{});
        // Keyboard layout translation (evdev code + compositor keymap → UTF-8 text for
        // `on_text`). FFI is hand-declared in src/xkb.zig, so only the library is linked.
        zrame.linkSystemLibrary("xkbcommon", .{});
        // Tray icon (StatusNotifierItem) talks to the session bus through sd-bus. We
        // hand-declare the FFI, so no headers are needed — just link libsystemd.
        zrame.linkSystemLibrary("systemd", .{ .use_pkg_config = .no });

        for (protocol_xmls) |xml| {
            const scan = b.addSystemCommand(&.{ "wayland-scanner", "private-code" });
            scan.addFileArg(.{ .cwd_relative = xml });
            const c_file = scan.addOutputFileArg("protocol.c");
            zrame.addCSourceFile(.{ .file = c_file });
        }
    } else if (target.result.os.tag == .windows) {
        zrame.linkSystemLibrary("user32", .{});
        // GDI: the DIB section + memory DC behind the layered-window (UpdateLayeredWindow)
        // glass presentation. The rounded panel + drop shadow are painted client-side, so no
        // DWM is needed (and none is used — the glass shows even under Wine).
        zrame.linkSystemLibrary("gdi32", .{});
    }

    // `zig build test` — every `test` block in the library.
    const mod_tests = b.addTest(.{ .root_module = zrame });
    const run_mod_tests = b.addRunArtifact(mod_tests);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_mod_tests.step);

    // Examples: `zig build run-hello`, `zig build run-frames`. `tray` and `menu` exercise
    // Linux-desktop-only surfaces (StatusNotifierItem, KDE global menu) and drive the
    // Wayland poll loop directly, so they only build on Linux; the rest are portable.
    const addExample = struct {
        fn add(bb: *std.Build, t: anytype, o: anytype, zr: *std.Build.Module, zi: *std.Build.Dependency, comptime name: []const u8) void {
            const exe = bb.addExecutable(.{
                .name = name,
                .root_module = bb.createModule(.{
                    .root_source_file = bb.path("examples/" ++ name ++ ".zig"),
                    .target = t,
                    .optimize = o,
                    .imports = &.{
                        .{ .name = "zrame", .module = zr },
                        .{ .name = "zicro", .module = zi.module("zicro") },
                    },
                }),
            });
            bb.installArtifact(exe);
            const run_cmd = bb.addRunArtifact(exe);
            const run_step = bb.step("run-" ++ name, "Run the " ++ name ++ " example");
            run_step.dependOn(&run_cmd.step);
        }
    }.add;
    inline for (.{ "hello", "frames", "scroll", "widgets" }) |name| addExample(b, target, optimize, zrame, zicro, name);
    if (target.result.os.tag == .linux) {
        inline for (.{ "tray", "menu", "runtime" }) |name| addExample(b, target, optimize, zrame, zicro, name);
    }

    // A loadable plugin built as a shared library, plus a host that dlopens it:
    // `zig build run-plugin`. The host hardcodes a `.so` path, so build it on Linux only.
    if (target.result.os.tag == .linux) {
    const clock = b.addLibrary(.{
        .name = "zrame_clock",
        .linkage = .dynamic,
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/plugin_clock.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zrame", .module = zrame }},
        }),
    });
    b.installArtifact(clock);

    const host_exe = b.addExecutable(.{
        .name = "plugin_host",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/plugin_host.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zrame", .module = zrame }},
        }),
    });
    b.installArtifact(host_exe);
    const host_run = b.addRunArtifact(host_exe);
    // The host dlopens zig-out/lib/libzrame_clock.so, so make sure it's installed first.
    host_run.step.dependOn(b.getInstallStep());
    if (b.args) |args| host_run.addArgs(args);
    const host_step = b.step("run-plugin", "Run the dlopen plugin host example");
    host_step.dependOn(&host_run.step);
    }

    // `zig build web` — the WebAssembly glass window in a browser tab. wasm32-freestanding,
    // no libc/Wayland/sd-bus: a fresh zicro module rooted at zicro's web_root (paint + text
    // + the web Window backend) and a zrame module rooted at its web_root (chrome + panels).
    {
        const wasm_target = b.resolveTargetQuery(.{ .cpu_arch = .wasm32, .os_tag = .freestanding });
        const zicro_web = b.createModule(.{
            .root_source_file = zicro.path("src/web_root.zig"),
            .target = wasm_target,
            .optimize = .ReleaseSmall,
        });
        zicro_web.addIncludePath(zicro.path("vendor/stb"));
        zicro_web.addCSourceFile(.{
            .file = zicro.path("vendor/stb/stb_truetype_web.c"),
            .flags = &.{ "-O2", "-fno-sanitize=undefined" },
        });
        const zrame_web = b.createModule(.{
            .root_source_file = b.path("src/web_root.zig"),
            .target = wasm_target,
            .optimize = .ReleaseSmall,
            .imports = &.{.{ .name = "zicro", .module = zicro_web }},
        });
        const web_mod = b.createModule(.{
            .root_source_file = b.path("examples/web.zig"),
            .target = wasm_target,
            .optimize = .ReleaseSmall,
            .imports = &.{.{ .name = "zrame", .module = zrame_web }},
        });
        const web_exe = b.addExecutable(.{ .name = "zrame", .root_module = web_mod });
        web_exe.entry = .disabled;
        web_exe.rdynamic = true;
        const install_wasm = b.addInstallArtifact(web_exe, .{ .dest_dir = .{ .override = .{ .custom = "web" } } });
        const copy_html = b.addInstallFileWithDir(b.path("web/index.html"), .{ .custom = "web" }, "index.html");
        const web_step = b.step("web", "Build the WebAssembly glass-window demo into zig-out/web");
        web_step.dependOn(&install_wasm.step);
        web_step.dependOn(&copy_html.step);
    }

    // `zig build android` — compile-check the Android backend (issue #11) for
    // aarch64-linux-android. A build-obj against a fresh zicro android module: it verifies
    // window_android.zig type-checks and codegens; the .so link + APK is zicro's #10.
    {
        const android_target = b.resolveTargetQuery(.{ .cpu_arch = .aarch64, .os_tag = .linux, .abi = .android });
        const zicro_android = b.createModule(.{
            .root_source_file = zicro.path("src/android_root.zig"),
            .target = android_target,
            .optimize = .ReleaseSmall,
        });
        zicro_android.addIncludePath(zicro.path("vendor/stb")); // stb_truetype.h for text.zig's cImport
        const check_mod = b.createModule(.{
            .root_source_file = b.path("src/android_check.zig"),
            .target = android_target,
            .optimize = .ReleaseSmall,
            .imports = &.{.{ .name = "zicro", .module = zicro_android }},
        });
        const and_obj = b.addObject(.{ .name = "zrame-android", .root_module = check_mod });
        const android_step = b.step("android", "Compile-check the Android backend for aarch64-linux-android");
        android_step.dependOn(&and_obj.step);
    }
}
